#!/bin/bash
layout=$(hyprctl devices | grep 'active keymap' | head -1 | xargs)

standard_layout="active keymap: English (UK, Macintosh)"
intl_layout="active keymap: English (UK, Macintosh, intl.)"

if [ "$layout" == "$standard_layout" ]; then
	echo "EN"
elif [[ "$layout" = "$intl_layout" ]]; then
	echo "INTL"
fi